name: GitHub Snake Game

on:
  schedule:
    # Runs every day at midnight UTC
    - cron: "0 0 * * *"

  # Allows manual execution
  workflow_dispatch:

  # Runs when pushing to main
  push:
    branches:
      - main

jobs:
  generate:
    runs-on: ubuntu-latest
    timeout-minutes: 10

    steps:
      # Checkout repository
      - name: Checkout Repository
        uses: actions/checkout@v4

      # Generate snake animations
      - name: Generate GitHub Contributions Snake Animations
        uses: Platane/snk@v3
        with:
          github_user_name: ${{ github.repository_owner }}

          outputs: |
            dist/snake.svg
            dist/snake-dark.svg?palette=github-dark

        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      # Deploy generated files
      - name: Deploy Snake Animation
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./dist
          publish_branch: snake-output
          commit_message: "Update snake animation [skip ci]"
